apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-demo
  name: hello-demo
  namespace: development
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: hello-demo
    tier: backend
